// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.20.
// **********************************************************************

#ifndef __T2TARSOBJ_H_
#define __T2TARSOBJ_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace T2App
{
    struct T2TarsRequest : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "T2App.T2TarsRequest";
        }
        static string MD5()
        {
            return "5292d5ad935f65bf0453ecd48410d2fa";
        }
        T2TarsRequest()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            funcNo = 0;
            seqNo = 0;
            data.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            if (funcNo != 0)
            {
                _os.write(funcNo, 1);
            }
            if (seqNo != 0)
            {
                _os.write(seqNo, 2);
            }
            if (!data.empty())
            {
                _os.write(data, 3);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(funcNo, 1, false);
            _is.read(seqNo, 2, false);
            _is.read(data, 3, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["funcNo"] = tars::JsonOutput::writeJson(funcNo);
            p->value["seqNo"] = tars::JsonOutput::writeJson(seqNo);
            p->value["data"] = tars::JsonOutput::writeJson(data);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(funcNo,pObj->value["funcNo"], false);
            tars::JsonInput::readJson(seqNo,pObj->value["seqNo"], false);
            tars::JsonInput::readJson(data,pObj->value["data"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(funcNo,"funcNo");
            _ds.display(seqNo,"seqNo");
            _ds.display(data,"data");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(funcNo, true);
            _ds.displaySimple(seqNo, true);
            _ds.displaySimple(data, false);
            return _os;
        }
    public:
        tars::Int32 funcNo;
        tars::Int32 seqNo;
        map<std::string, std::string> data;
    };
    inline bool operator==(const T2TarsRequest&l, const T2TarsRequest&r)
    {
        return l.funcNo == r.funcNo && l.seqNo == r.seqNo && l.data == r.data;
    }
    inline bool operator!=(const T2TarsRequest&l, const T2TarsRequest&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const T2TarsRequest&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,T2TarsRequest&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct T2TarsResponse : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "T2App.T2TarsResponse";
        }
        static string MD5()
        {
            return "d4414eef53d3c8c215758ddec5c679a3";
        }
        T2TarsResponse()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            code = 0;
            msg = "";
            seqNo = 0;
            data.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            if (code != 0)
            {
                _os.write(code, 1);
            }
            if (msg != "")
            {
                _os.write(msg, 2);
            }
            if (seqNo != 0)
            {
                _os.write(seqNo, 3);
            }
            if (!data.empty())
            {
                _os.write(data, 4);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(code, 1, false);
            _is.read(msg, 2, false);
            _is.read(seqNo, 3, false);
            _is.read(data, 4, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["code"] = tars::JsonOutput::writeJson(code);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            p->value["seqNo"] = tars::JsonOutput::writeJson(seqNo);
            p->value["data"] = tars::JsonOutput::writeJson(data);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(code,pObj->value["code"], false);
            tars::JsonInput::readJson(msg,pObj->value["msg"], false);
            tars::JsonInput::readJson(seqNo,pObj->value["seqNo"], false);
            tars::JsonInput::readJson(data,pObj->value["data"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(code,"code");
            _ds.display(msg,"msg");
            _ds.display(seqNo,"seqNo");
            _ds.display(data,"data");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(code, true);
            _ds.displaySimple(msg, true);
            _ds.displaySimple(seqNo, true);
            _ds.displaySimple(data, false);
            return _os;
        }
    public:
        tars::Int32 code;
        std::string msg;
        tars::Int32 seqNo;
        vector<map<std::string, std::string> > data;
    };
    inline bool operator==(const T2TarsResponse&l, const T2TarsResponse&r)
    {
        return l.code == r.code && l.msg == r.msg && l.seqNo == r.seqNo && l.data == r.data;
    }
    inline bool operator!=(const T2TarsResponse&l, const T2TarsResponse&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const T2TarsResponse&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,T2TarsResponse&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


    /* callback of async proxy for client */
    class T2TarsObjPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~T2TarsObjPrxCallback(){}
        virtual void callback_invoke(tars::Int32 ret,  const T2App::T2TarsResponse& rsp)
        { throw std::runtime_error("callback_invoke() override incorrect."); }
        virtual void callback_invoke_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_invoke_exception() override incorrect."); }
        virtual void callback_invoke(tars::Int32 ret, T2App::T2TarsResponse&&  rsp)
        { callback_invoke(ret, rsp); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __T2TarsObj_all[]=
            {
                "invoke"
            };
            auto it = _msg_->response->status.find("TARS_FUNC");
            pair<string*, string*> r = equal_range(__T2TarsObj_all, __T2TarsObj_all+1, (it==_msg_->response->status.end())?_msg_->request.sFuncName:it->second);
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __T2TarsObj_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_invoke_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    T2App::T2TarsResponse rsp;
                    _is.read(rsp, 2, true);
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                            _p_->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, "", getModuleName(), "invoke", 0, _trace_param_, "");
                    }

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_invoke(_ret, std::move(rsp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<T2TarsObjPrxCallback> T2TarsObjPrxCallbackPtr;

    //callback of promise async proxy for client
    class T2TarsObjPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~T2TarsObjPrxCallbackPromise(){}
    public:
        struct Promiseinvoke: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            T2App::T2TarsResponse rsp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< T2TarsObjPrxCallbackPromise::Promiseinvoke > PromiseinvokePtr;

        T2TarsObjPrxCallbackPromise(const tars::Promise< T2TarsObjPrxCallbackPromise::PromiseinvokePtr > &promise)
        : _promise_invoke(promise)
        {}
        
        virtual void callback_invoke(const T2TarsObjPrxCallbackPromise::PromiseinvokePtr &ptr)
        {
            _promise_invoke.setValue(ptr);
        }
        virtual void callback_invoke_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:invoke_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_invoke.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< T2TarsObjPrxCallbackPromise::PromiseinvokePtr > _promise_invoke;

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __T2TarsObj_all[]=
            {
                "invoke"
            };

            pair<string*, string*> r = equal_range(__T2TarsObj_all, __T2TarsObj_all+1, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __T2TarsObj_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_invoke_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    T2TarsObjPrxCallbackPromise::PromiseinvokePtr ptr (new T2TarsObjPrxCallbackPromise::Promiseinvoke());

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->rsp, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_invoke_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_invoke_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_invoke(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<T2TarsObjPrxCallbackPromise> T2TarsObjPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class T2TarsObjCoroPrxCallback: public T2TarsObjPrxCallback
    {
    public:
        virtual ~T2TarsObjCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __T2TarsObj_all[]=
            {
                "invoke"
            };

            pair<string*, string*> r = equal_range(__T2TarsObj_all, __T2TarsObj_all+1, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __T2TarsObj_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_invoke_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        T2App::T2TarsResponse rsp;
                        _is.read(rsp, 2, true);
                        setResponseContext(_msg_->response->context);

                        callback_invoke(_ret, std::move(rsp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_invoke_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_invoke_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<T2TarsObjCoroPrxCallback> T2TarsObjCoroPrxCallbackPtr;

    /* proxy for client */
    class T2TarsObjProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 invoke(const T2App::T2TarsRequest & req,T2App::T2TarsResponse &rsp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(req, 1);
            _os.write(rsp, 2);
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["req"] = tars::JsonOutput::writeJson(req);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "invoke", 0, _trace_param_, "");
            }

            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"invoke", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(rsp, 2, true);
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CR, _is.size());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CR), TRACE_ANNOTATION_CR, tars_moduleName(), tars_name(), "invoke", 0, _trace_param_, "");
            }

            return _ret;
        }

        void async_invoke(T2TarsObjPrxCallbackPtr callback,const T2App::T2TarsRequest &req,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
            if (_pSptd_ && _pSptd_->_traceCall)
            {
                _pSptd_->newSpan();
                string _trace_param_;
                int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_CS, _os.getLength());
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value["req"] = tars::JsonOutput::writeJson(req);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_CS), TRACE_ANNOTATION_CS, tars_moduleName(), tars_name(), "invoke", 0, _trace_param_, "");
            }
            tars_invoke_async(tars::TARSNORMAL,"invoke", _os, context, _mStatus, callback);
        }
        
        tars::Future< T2TarsObjPrxCallbackPromise::PromiseinvokePtr > promise_async_invoke(const T2App::T2TarsRequest &req,const map<string, string>& context)
        {
            tars::Promise< T2TarsObjPrxCallbackPromise::PromiseinvokePtr > promise;
            T2TarsObjPrxCallbackPromisePtr callback (new T2TarsObjPrxCallbackPromise(promise));

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"invoke", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_invoke(T2TarsObjCoroPrxCallbackPtr callback,const T2App::T2TarsRequest &req,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"invoke", _os, context, _mStatus, callback, true);
        }

        T2TarsObjProxy* tars_hash(size_t key)
        {
            return (T2TarsObjProxy*)ServantProxy::tars_hash(key);
        }

        T2TarsObjProxy* tars_consistent_hash(size_t key)
        {
            return (T2TarsObjProxy*)ServantProxy::tars_consistent_hash(key);
        }

        T2TarsObjProxy* tars_open_trace(bool traceParam = false)
        {
            return (T2TarsObjProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        T2TarsObjProxy* tars_set_timeout(int msecond)
        {
            return (T2TarsObjProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "T2TarsObjProxy"; }
    };
    typedef tars::TC_AutoPtr<T2TarsObjProxy> T2TarsObjPrx;

    /* servant for server */
    class T2TarsObj : public tars::Servant
    {
    public:
        virtual ~T2TarsObj(){}
        virtual tars::Int32 invoke(const T2App::T2TarsRequest & req,T2App::T2TarsResponse &rsp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 invoke(T2App::T2TarsRequest && req,T2App::T2TarsResponse &rsp,tars::TarsCurrentPtr _current_) 
        { return invoke(req, rsp, _current_); }
        static void async_response_invoke(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const T2App::T2TarsResponse &rsp)
        {
            size_t _rsp_len_ = 0;
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("rsp", rsp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _tarsAttr_);
                _rsp_len_ = sTupResponseBuffer.size();
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
                _rsp_len_ = sJsonResponseBuffer.size();
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(rsp, 2);

                _rsp_len_ = _os.getLength();
                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
            if (_current_->isTraced())
            {
                string _trace_param_;
                int _trace_param_flag_ = ServantProxyThreadData::needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _current_->getTraceKey(), _rsp_len_);
                if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                {
                    tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                    _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                    _p_->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                    _trace_param_ = tars::TC_Json::writeValue(_p_);
                }
                else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                {
                    _trace_param_ = "{\"trace_param_over_max_len\":true}";
                }
                if(_current_->getServantHandle())
                {
                    TARS_TRACE(_current_->getTraceKey(), TRACE_ANNOTATION_SS, "", _current_->getModuleName(), "invoke", 0, _trace_param_, "");
                }
            }

        }
        static void async_response_push_invoke(tars::CurrentPtr _current_, tars::Int32 _ret, const T2App::T2TarsResponse &rsp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(rsp, 2);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"invoke", _os, _context);
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __T2App__T2TarsObj_all[]=
            {
                "invoke"
            };

            pair<string*, string*> r = equal_range(__T2App__T2TarsObj_all, __T2App__T2TarsObj_all+1, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __T2App__T2TarsObj_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    T2App::T2TarsRequest req;
                    T2App::T2TarsResponse rsp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("req", req);
                        _tarsAttr_.getByDefault("rsp", rsp, rsp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(req, _jsonPtr->value["req"], true);
                        tars::JsonInput::readJson(rsp, _jsonPtr->value["rsp"], false);
                    }
                    else
                    {
                        _is.read(req, 1, true);
                        _is.read(rsp, 2, false);
                    }
                    ServantProxyThreadData *_pSptd_ = ServantProxyThreadData::getData();
                    if (_pSptd_ && _pSptd_->_traceCall)
                    {
                        string _trace_param_;
                        int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SR, _is.size());
                        if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                        {
                            tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                            _p_->value["req"] = tars::JsonOutput::writeJson(req);
                            _trace_param_ = tars::TC_Json::writeValue(_p_);
                        }
                        else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                        {
                            _trace_param_ = "{\"trace_param_over_max_len\":true}";
                        }
                        TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SR), TRACE_ANNOTATION_SR, "", getModuleName(), "invoke", 0, _trace_param_, "");
                    }

                    tars::Int32 _ret = invoke(std::move(req),rsp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("rsp", rsp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(rsp, 2);
                            _os.swap(_sResponseBuffer);
                        }
                        if (_pSptd_ && _pSptd_->_traceCall)
                        {
                            string _trace_param_;
                            int _trace_param_flag_ = _pSptd_->needTraceParam(ServantProxyThreadData::TraceContext::EST_SS, _sResponseBuffer.size());
                            if (ServantProxyThreadData::TraceContext::ENP_NORMAL == _trace_param_flag_)
                            {
                                tars::JsonValueObjPtr _p_ = new tars::JsonValueObj();
                                _p_->value[""] = tars::JsonOutput::writeJson(_ret);
                                _p_->value["rsp"] = tars::JsonOutput::writeJson(rsp);
                                _trace_param_ = tars::TC_Json::writeValue(_p_);
                            }
                            else if(ServantProxyThreadData::TraceContext::ENP_OVERMAXLEN == _trace_param_flag_)
                            {
                                _trace_param_ = "{\"trace_param_over_max_len\":true}";
                            }
                            TARS_TRACE(_pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS), TRACE_ANNOTATION_SS, "", getModuleName(), "invoke", 0, _trace_param_, "");
                        }

                    }
                    else if(_pSptd_ && _pSptd_->_traceCall)
                    {
                        _current->setTrace(_pSptd_->_traceCall, _pSptd_->getTraceKey(ServantProxyThreadData::TraceContext::EST_SS));
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
